### PR TITLE
helpers contains setting up tools

### LINKED ISSUE #24: The library copy function should do all the copying work
Right now the target file is truncated before going through the copy function. So bmap::copy should absorb that function and sort it. 
 The main file does not need to carry low level functions, should focus on sorting the commands.

### PR DESCRIPTION
**Pull request by Razaloc**
helpers mod contains functions and structs needed to setup common inputs/outputs

Closes #24 

Signed-off-by: Rafael Garcia Ruiz <rafael.garcia@collabora.com>

### CODE REVIEW

**Comment by Razaloc** [comment]
this is meant to be a middle step of cleaning the main function of things that should not be there. The intention is for it to detect if target is a file or a bloc device and prepare it (truncate or do specific optimization)

**Comment by Razaloc** [comment]
Intending not to touch the `bmap::copy` function, and still leave the main function clearer I've created a `helpers` mod to take all work of setting up inputs and outputs for it. That would leave also a separate place for filtering and dealing with different kinds of inputs/outputs.

**Comment by obbardc** [comment]
@Razaloc Can this be closed?

**Comment by Razaloc** [comment]
Sure

**Pull request closed without merging**
